### ISSUE TITLE
深度os python2.7.13报错

### ISSUE THREAD

**Issue by snailrobert** [yueyoum/renren-relationship#6]
Traceback (most recent call last):
  File "local_graph.py", line 202, in <module>
    g.import_data(data)
  File "local_graph.py", line 50, in import_data
    for n in self.G.nodes():
RuntimeError: dictionary changed size during iteration

修改成list包装后，报错：
Traceback (most recent call last):
  File "local_graph.py", line 202, in <module>
    g.import_data(data)
  File "local_graph.py", line 57, in import_data
    self.max_degree_value = max(self.degree.values())
AttributeError: 'DegreeView' object has no attribute 'values'

**Comment by snailrobert** [comment]
希望能帮助解决一下，谢谢。

**Comment by xiaoxiaoyao** [comment]
这个项目应该早就不更新了，淡定自己写吧
@snailrobert
